project_id = "ykfiubiogxetbgdkavep"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Functions configuration
[functions.embed-article]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

[functions.process-embeddings]
verify_jwt = false

[functions.ingest-content]
verify_jwt = false